export const requests = {
  login: 'api/user/login',
  loginPage: '/login',
  getFixedAssets: 'api/asset',
  singleFixedAsset: 'api/asset',
  getInventories: 'api/inventory/onlyall',
  singleInventory: 'api/inventory',
  getUsers: 'api/user/onlyall',
  singleUser: 'api/user',
  selectUserRole: '/select-user-role',
  userFixedAsset: '/user/fixed-asset',
  userFixedAssetConfirm: '/user/fixed-asset/confirm',
  adminPanel: '/admin-panel',
  accountantPanel: '/accountant-panel',
  userManagement: '/user-management',
  userCreate: '/user-management/create',
  fixedAssetManagement: '/fixed-asset-management',
  fixedAssetCreate: '/fixed-asset-management/create',
  issueManagement: '/issue-management',
  issuePage: '/issue',
  inventoryManagement: '/inventory-management',
  inventoryCreate: '/inventory-management',
};
